name: MapMarkers
version: 0.1.1
decsription: Generates Markers on an Overviewer generated map
author: 1am3r
website: http://1am3r.github.com/MapMarkers/

main: com.github._1am3r.MapMarkers.MapMarkers
