name: PlayerMarkers
version: 0.1.2
decsription: Generates Markers on an Overviewer generated map
author: 1am3r
website: http://1am3r.github.com/PlayerMarkers/

main: com.github._1am3r.PlayerMarkers.PlayerMarkers
